-- 001_core_schema.down.sql
-- Reverse the core schema

DROP TABLE IF EXISTS ingestion_jobs CASCADE;
DROP TABLE IF EXISTS telemetry_datasets CASCADE;
DROP TABLE IF EXISTS weather_data CASCADE;
DROP TABLE IF EXISTS laps CASCADE;
DROP TABLE IF EXISTS session_results CASCADE;
DROP TABLE IF EXISTS driver_seasons CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS circuits CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS regulation_eras CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
